services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - docker_secrets.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  userapi:
    build: 
      context: .
      dockerfile: ZiiqueSocialBackend/Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    env_file:
      - docker_secrets.env

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    env_file:
      - docker_secrets.env
    ports:
      - "8090:8080"
    command: start-dev

volumes:
  pgdata:
